---
- name: "Update apt cache"
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: "Upgrade apt packages"
  become: true
  apt:
    upgrade: safe

- name: Install basic packages
  become: true
  apt:
    state: present
    pkg:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - net-tools
      - ufw
      - fail2ban
