version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "mix"
    directory: "/platform_umbrella"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/platform_umbrella/apps/control_server_web/assets"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/platform_umbrella/apps/home_base_web/assets"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/static_pages"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/rust_utils"
    schedule:
      interval: "daily"
