---
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: '/platform_umbrella/apps/control_server_web/assets'
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: '/platform_umbrella/apps/home_base_web/assets'
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: '/project_templates/pastebin'
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: '/cli'
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: '/project_templates/pastebin'
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: '/ops/eks/terraform'
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: '/ops/aws/terraform'
    schedule:
      interval: daily
