version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: mix
    directory: "/plattform_umbrella"
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/plattform_umbrella/apps/control_server_web/assets"
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/plattform_umbrella/apps/home_base_web/assets"
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/static"
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: "/rust_utils"
    schedule:
      interval: daily
