version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: mix
    directory: '/platform_umbrella'
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: '/dev'
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: '/static'
    schedule:
      interval: daily
