[build]
publish = "dist"
base = "static"
command = "npm install; npm run build"

[build.processing.html]
pretty_urls = false

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
