---
- name: Install Wireguard packages
  become: true
  apt:
    state: present
    pkg:
      - wireguard
      - linux-headers-{{ ansible_kernel }}

- name: Ensure Wireguard DKMS package is removed
  become: true
  apt:
    name:
      - wireguard-dkms
    state: absent

- name: Enable IPV4 forwarding
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_set: yes

- name: Enable Wireguard kernel module
  become: true
  modprobe:
    name: wireguard
    state: present
  register: wireguard_module_enabled
  until: wireguard_module_enabled is succeeded
  retries: 10
  delay: 10
  failed_when: wireguard_module_enabled is failure

- name: Configure Wireguard
  become: true
  template:
    src: ./templates/server.conf
    dest: "/etc/wireguard/{{ gateway.tunnel }}.conf"
    owner: root
    group: root
  notify:
    - new wireguard config

- name: Start Wireguard service
  become: true
  service:
    name: "wg-quick@{{ gateway.tunnel }}"
    state: "started"
    enabled: "yes"
