defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - swa.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: 'epoch_{epoch:03d}'
  monitor: 'val/loss'
  mode: 'min'
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: 'val/loss'
  patience: 3
  mode: 'min'
  min_delta: 1.0e-3

model_summary:
  max_depth: -1

stochastic_weight_averaging:
  swa_lrs: 5.0e-3
