---
- name: Prepare
  hosts: k3s_cluster
  become: true
  roles:
    - role: bootstrap
    - role: download

- name: Master
  hosts: master
  become: true
  roles:
    - role: k3s/master

- name: Nodes
  hosts: node
  become: true
  roles:
    - role: k3s/node
