[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# Todo: pin to versions before releasing
assert_cmd = { version = "*" }
clap = { version = "*", features = ["derive"] }
exitcode = { version = "*" }
env_logger = { version = "*" }
futures = { version = "*" }
hyper = { version = "*" }
kube-client = { version = "*" }
k8s-openapi = { version = "*", features = ["v1_26"] }
log = { version = "*" }
predicates = { version = "*" }
tokio = { version = "*", features = ["full"] }
tower-test = { version = "*" }
