[package]
name = "bcli"
version = "0.7.0"
edition = "2021"

[dependencies]
assert_cmd = { version = "2.0.10" }
clap = { version = "4.3.3", features = ["derive", "color", "usage"] }
clap-verbosity-flag = { version = "2.0.1" }
color-eyre = { version = "0.6.2" }
bollard = { version = "0.14.0", features = ["time"] }
dirs = { version = "5.0.1" }
eyre = { version = "0.6.8" }
futures = { version = "0.3.28" }
hyper = { version = "0.14.25" }
ipnet = "2.7.2"
k8s-openapi = { version = "0.18.0", features = ["v1_26"] }
kube-client = { version = "0.82.1", features = ["ws", "oauth"] }
kube-runtime = { version = "0.82.1" }
reqwest = { version = "0.11.18", features = ["json", "gzip"] }
serde = { version = "1.0.163" }
serde_json = { version = "1.0.95", default-features = true }
tempfile = { version = "3.5.0" }
thiserror = { version = "1.0.40" }
time = { version = "0.3.21", features = ["serde", "serde-human-readable"] }
tokio = { version = "1.28.2", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["net", "time"] }
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.17" }
url = { version = "2.4.0" }
uuid = { version = "1.3.3", features = ["v4", "v6", "serde"] }

[profile.release]
strip = true
lto = "thin"
opt-level = "z"
codegen-units = 1

[profile.dev.package.backtrace]
opt-level = 3
