[package]
name = "bcli"
version = "0.4.0"
edition = "2021"

[dependencies]
# Todo: pin to versions before releasing
assert_cmd = { version = "2.0.8" }
async-process = { version = "1.6.0" }
clap = { version = "4.1.6", features = ["derive", "color", "usage"] }
dirs = { version = "4.0.0" }
env_logger = { version = "0.10.0" }
exitcode = { version = "1.1.2" }
futures = { version = "0.3.26" }
hyper = { version = "0.14.24" }
k8s-openapi = { version = "0.17.0", features = ["v1_26"] }
kube-client = { version = "0.79.0" }
log = { version = "0.4.17" }
predicates = { version = "2.1.5" }
reqwest = { version = "0.11.14" }
retry = {version ="2.0.0"}
serde_json = { version = "1.0.93", default-features = true }
signal-hook = { version = "0.3.15" }
tempdir = { version = "0.3.7" }
tokio = { version = "1.25.0", features = ["full"] }
tower-test = { version = "0.4.0" }
url = { version = "2.3.1" }

[profile.release]
strip = true
lto = "thin"
opt-level = "z"
codegen-units = 1
