[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# Todo: pin to versions before releasing
assert_cmd = { version = "*" }
clap = { version = "*", features = ["derive"] }
exitcode = { version = "*" }
env_logger = { version = "*" }
log = { version = "*" }
predicates = { version = "*" }
