[package]
name = "bcli"
version = "0.4.0"
edition = "2021"

[dependencies]
assert_cmd = { version = "2.0.10" }
bollard = { version = "0.14.0", features = ["time"] }
clap = { version = "4.2.1", features = ["derive", "color", "usage"] }
clap-verbosity-flag = { version = "2.0.1" }
color-eyre = { version = "0.6.2" }
dirs = { version = "5.0.0" }
eyre = { version = "0.6.8" }
futures = { version = "0.3.28" }
hyper = { version = "0.14.25" }
k8s-openapi = { version = "0.17.0", features = ["v1_26"] }
kube-client = { version = "0.80.0", features = ["ws", "oauth"] }
predicates = { version = "3.0.2" }
reqwest = { version = "0.11.16", features = ["json", "gzip"] }
serde = { version = "1.0.159" }
serde_json = { version = "1.0.95", default-features = true }
tempfile = { version = "3.5.0" }
thiserror = { version = "1.0.40" }
time = { version = "0.3.20", features = ["serde", "serde-human-readable"] }
tokio = { version = "1.27.0", features = ["full"] }
tokio-stream = { version = "0.1.12", features = ["net", "time"] }
tower-test = { version = "0.4.0" }
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.16" }
url = { version = "2.3.1" }
uuid = { version = "1.3.0", features = ["v4", "v6", "serde"] }

[profile.release]
strip = true
lto = "thin"
opt-level = "z"
codegen-units = 1

[profile.dev.package.backtrace]
opt-level = 3
