[package]
name = "bcli"
version = "0.4.0"
edition = "2021"

[dependencies]
# Todo: pin to versions before releasing
assert_cmd = { version = "2.0.10" }
async-process = { version = "1.6.0" }
clap = { version = "4.1.11", features = ["derive", "color", "usage"] }
dirs = { version = "5.0.0" }
env_logger = { version = "0.10.0" }
exitcode = { version = "1.1.2" }
futures = { version = "0.3.27" }
hyper = { version = "0.14.25" }
k8s-openapi = { version = "0.17.0", features = ["v1_26"] }
kube-client = { version = "0.80.0" }
log = { version = "0.4.17" }
predicates = { version = "3.0.2" }
reqwest = { version = "0.11.16" }
retry = {version ="2.0.0"}
serde_json = { version = "1.0.94", default-features = true }
signal-hook = { version = "0.3.15" }
tempfile = { version = "3.4.0" }
tokio = { version = "1.26.0", features = ["full"] }
tower-test = { version = "0.4.0" }
url = { version = "2.3.1" }

[profile.release]
strip = true
lto = "thin"
opt-level = "z"
codegen-units = 1
