[package]
name = "bcli"
version = "0.7.0"
edition = "2021"

[dependencies]
assert_cmd = { version = "2.0.12" }
clap = { version = "4.4.3", features = ["derive", "color", "usage"] }
clap-verbosity-flag = { version = "2.0.1" }
color-eyre = { version = "0.6.2" }
bollard = { version = "0.15.0", features = ["time", "ssl"] }
dirs = { version = "5.0.1" }
eyre = { version = "0.6.8" }
futures = { version = "0.3.28" }
hyper = { version = "0.14.27" }
ipnet = { version = "2.8.0" }
k8s-openapi = { version = "0.20.0", features = ["v1_26"] }
kube-client = { version = "0.86.0", features = ["ws", "oauth", "rustls-tls"] }
kube-runtime = { version = "0.86.0" }
reqwest = { version = "0.11.20", default-features = false, features = [
  "async-compression",
  "gzip",
  "deflate",
  "brotli",
  "json",
  "rustls-tls",
] }
serde = { version = "1.0.188" }
serde_json = { version = "1.0.107", default-features = true }
tempfile = { version = "3.8.0" }
thiserror = { version = "1.0.48" }
time = { version = "0.3.28", features = ["serde", "serde-human-readable"] }
tokio = { version = "1.32.0", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["net", "time"] }
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.17" }
url = { version = "2.4.1" }
uuid = { version = "1.4.1", features = ["v4", "v6", "serde"] }

[profile.release]
strip = true
lto = "thin"
opt-level = "z"
codegen-units = 1

[profile.dev.package.backtrace]
opt-level = 3
