[package]
authors = ["Elliott Clark <elliott@batteriesincl.com>"]
edition = "2018"
name = "cli"
version = "0.1.0"

[dependencies]

common = {path = "../common"}
# Concurrency
futures = "0.3.17"
tokio = { version = "1.11.0", features = ["full"] }

# pinning the version to 1.17.x since
# GKE is there it makes for a good stable target.
k8s-openapi = { version = "0.13.0", features = ["v1_17"], default-features = false }
kube = { version = "0.60.0", features = ["derive"] }

# Logging/Tracing
tracing = "0.1.27"
clap = "~2.33.3"

# Yaml
serde = "1.0.130"
serde_json = "1.0.67"
serde_yaml = "0.8.20"
