[package]
authors = ["Elliott Clark <elliott@batteriesincl.com>"]
edition = "2018"
name = "cli"
version = "0.1.0"

[dependencies]
common = { path = "../common" }
# Concurrency
futures = "0.3.21"
tokio = { version = "1.16.1", features = ["full"] }
kube = { version = "0.66.0", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.14.0", default-features = false, features = [
  "v1_20"
] }
# Logging/Tracing
tracing = "0.1.30"
clap = "~3.0.14"
# Yaml
serde = "1.0.136"
serde_json = "1.0.78"
serde_yaml = "0.8.23"
