[package]
authors = ["Elliott Clark <elliott@batteriesincl.com>"]
edition = "2018"
name = "cli"
version = "0.1.0"

[dependencies]
common = { path = "../common" }
# Concurrency
futures = "0.3.19"
tokio = { version = "1.15.0", features = ["full"] }
kube = { version = "0.66.0", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.13.1", default-features = false, features = [
  "v1_20"
] }
# Logging/Tracing
tracing = "0.1.29"
clap = "~3.0.10"
# Yaml
serde = "1.0.134"
serde_json = "1.0.76"
serde_yaml = "0.8.23"
