[package]
authors = ["Elliott Clark <elliott.neil.clark@gmail.com>"]
edition = "2018"
name = "cli"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

common = {path = "../common"}
# Concurrency
futures = "0.3.15"
tokio = { version = "1.5.0", features = ["full"] }

# pinning the version to 1.17.x since
# GKE is there it makes for a good stable target.
k8s-openapi = { version = "0.11.0", features = ["v1_17"], default-features = false }
kube = { version = "0.52.0", features = ["derive"] }

# Logging/Tracing
tracing = "0.1.26"
