name = "Batteries_included_tailwind"
license = "Private"
licenselink = ""
description = ""
homepage = "http://batteriesincl.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = ""
  homepage = ""

[build]
# Used by PurgeCSS
  writeStats = true

[security.exec]
  osEnv = ['.*']

[[headers]]
  for = "/*.jpg"

[headers.values]
  Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.png"

[headers.values]
  Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.css"

[headers.values]
  Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.js"

[headers.values]
  Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/webfonts/*"

[headers.values]
  Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*"

[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "no-referrer"
  Content-Security-Policy = "script-src 'self' 'unsafe-inline'"