apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_USER: batterydbuser
  POSTGRES_DB: bi
  POSTGRES_INITDB_ARGS: "--data-checksums"
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
