apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  url: http://battery-prometheus-prometheus.battery-core:9090/
  access: proxy
  isDefault: true
  jsonData:
    timeInterval: 30s