---
- name: Add ansible ppa
  ansible.builtin.apt_repository:
    repo: ppa:ansible/ansible

- name: Install basic packages
  apt:
    state: present
    pkg:
      - autoconf
      - automake
      - binutils
      - bison
      - build-essential
      - curl
      - dirmngr
      - file
      - fop
      - g++
      - gcc
      - gettext
      - git
      - gpg
      - libncurses5-dev
      - libreadline-dev
      - libssl-dev
      - libtool
      - libxslt-dev
      - libyaml-dev
      - make
      - patch
      - pkg-config
      - procps
      - unzip
      - xsltproc
      - zlib1g-dev
