# @package _global_

defaults:
  - _self_
  - data: tiny_shakespeare.yaml
  - model: tinygpt.yaml
  - logger: null
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: 'eval'

tags: ['dev']

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
