[package]
name = "entity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

sea-orm = { version = "0.11.2", features = [
  "with-json",
  "macros",
  "sqlx-postgres",
  "runtime-tokio-native-tls"
] }
serde = { version = "1.0.158", features = ["derive"] }
uuid = {version = "1.3.0", features = ["v4"]}
