[package]
name = "entity"
version = "0.7.0"
edition = "2021"

[dependencies]

sea-orm = { version = "0.11.3", features = [
  "with-json",
  "macros",
  "sqlx-postgres",
  "runtime-tokio-rustls",
] }
serde = { version = "1.0.166", features = ["derive"] }
uuid = { version = "1.3.4", features = ["v4"] }
