[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[dependencies]

sea-orm = { version = "0.11.3", features = [
  "with-json",
  "macros",
  "sqlx-postgres",
  "runtime-tokio-native-tls",
] }
serde = { version = "1.0.162", features = ["derive"] }
uuid = { version = "1.3.2", features = ["v4"] }
