newline_style = "Unix"
reorder_impl_items = true
wrap_comments = true
format_strings = true
merge_imports = true
normalize_comments = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
use_try_shorthand = true
edition = "2018"