---
- name: Install shell packages
  apt:
    state: present
    pkg:
      - zsh

- name: Ensure group "developers" exists
  ansible.builtin.group:
    name: developers
    state: present

- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: "Add the user"
  ansible.builtin.user:
    name: "{{user.username}}"
    comment: "{{user.name}}"
    group: admin
    groups: admin,adm,sudo,developers,docker
    shell: /usr/bin/zsh
  with_items: "{{users}}"
  loop_control:
    loop_var: user
    label: "{{ user.username }}"

- name: "No password sudo"
  copy:
    content: "{{user.username}} ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{user.username}}_nopasswd"
    mode: 0440
  with_items: "{{users}}"
  loop_control:
    loop_var: user
    label: "{{ user.username }}"

- name: Set authorized key for elliott
  authorized_key:
    user: elliott
    state: present
    key: "{{ lookup('file', '../pub_keys/elliott_ssh.pub') }}"

- name: Set authorized key for art
  authorized_key:
    user: art
    state: present
    key: "{{ lookup('file', '../pub_keys/art_ssh.pub') }}"

- name: Ensure .zshrc in place
  template:
    src: zshrc.j2
    dest: "/home/{{user.username}}/.zshrc"
    backup: true
    owner: "{{user.username}}"
    mode: 0640
  with_items: "{{users}}"
  loop_control:
    loop_var: user
    label: "{{ user.username }}"
