_target_: src.models.gpt_module.TinyGPT

net:
  _target_: src.models.components.gpt_net.GPTNet
  dim_model: 128

  num_heads: 4
  num_layers: 4

  embedding_dropout: 0.1
  head_dropout: 0.1
  multi_head_dropout: 0.1
  feed_forward_dropout: 0.1
  feed_forward_activation: 'gelu'
  feed_forward_layer_multiplier: 8

  vocab_size: 128
  sequence_length: 128

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 5.0e-3
  weight_decay: 0.0
