_target_: src.models.gpt_module.TinyGPT

net:
  _target_: src.models.components.xformers_net.XFormersNet
  dim_model: 128

  num_heads: 4
  num_layers: 4

  residual_dropout: 0.1
  attention_dropout: 0.1
  feed_forward_dropout: 0.1
  feed_forward_activation: 'gelu'
  feed_forward_layer_multiplier: 8

  sequence_length: 128
  vocab_size: 128

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 5.0e-5
  weight_decay: 0.0
