name: Nix

on:
  push:
    branches:
      - master
      - gh-readonly-queue/master/**
  pull_request:
    branches:
      - master

jobs:
  bcli:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: experimental-features = nix-command flakes
    - run: nix build .#bcli -L
  pastebin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: experimental-features = nix-command flakes
    - run: nix build .#pastebin -L
    - run: nix build .#pastebin-docker -L
  control-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: experimental-features = nix-command flakes
    - run: nix build .#control-server -L
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: experimental-features = nix-command flakes
    - run: nix flake check
