name: Nix

on:
  push:
    branches:
      - master
      - gh-readonly-queue/master/**
  pull_request:
    branches:
      - master

jobs:
  bcli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v1
      - run: nix build .#bcli -L
  pastebin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v1
      - run: nix build .#pastebin -L
      - run: nix build .#pastebin-docker -L
  control-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v1
      - run: nix build .#control-server -L
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v1
      - run: nix flake check
