name: Platform Umbrella

on:
  push:
    branches:
      - master
      - gh-readonly-queue/master/**
  pull_request:
    branches:
      - master

jobs:
  platform-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: batterydbuser
          POSTGRES_PASSWORD: 'batterypasswd'
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports: ['5432:5432']
    env:
      POSTGRES_HOST: localhost
      POSTGRES_USER: batterydbuser
      POSTGRES_PASSWORD: 'batterypasswd'
      MIX_ENV: test
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: experimental-features = nix-command flakes
    - run: nix develop --command bash ./dev/run-mix-test.sh
