name: Platform Umbrella

on:
  push:
    branches:
      - master
      - gh-readonly-queue/master/**
  pull_request:
    branches:
      - master

jobs:
  int-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: batteries-included
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush:
            ${{ !(github.ref == 'refs/heads/master' && github.event_name ==
            'push') }}
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Set up dev shell
        run: nix develop --command bash -c 'exit 0'
      - name: Set up kind
        run: nix develop --command bash -c 'kind create cluster'
      - name: Run integration tests
        run: nix develop --command bash -c "TRACE=1 bi ex-test-int"
      - name: Save screenshots as artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: wallaby-screenshots
          path: |
            platform_umbrella/apps/control_server_web/screenshots
  platform-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: batterydbuser
          POSTGRES_PASSWORD: 'batterypasswd'
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports: ['5432:5432']
    env:
      POSTGRES_HOST: localhost
      POSTGRES_USER: batterydbuser
      POSTGRES_PASSWORD: 'batterypasswd'
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: batteries-included
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush:
            ${{ !(github.ref == 'refs/heads/master' && github.event_name ==
            'push') }}
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix develop --command bash bi ex-test-deep
