name: Prettier

on:
  push:
    branches:
      - master
      - gh-readonly-queue/master/**
  pull_request:
    branches:
      - master

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          dry: true
          prettier_plugins:
            'prettier-plugin-sh prettier-plugin-go-template prettier-plugin-toml'
          prettier_options: --check .
